### ISSUE TITLE
XrayR可以report online users， 但是面板没有收到request

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/XrayR#10]
你的最新版本XrayR和v2board。

测试连接，XrayR节点 journalctl日志：

```
V2ray(ID=1) Report 1 online users
```

v2bord 面板节点，搜索alive关键词：
``` 
sudo cat /var/log/nginx/access.log | grep "alive"
 ```
为空， grep ``push''一大堆日志。 

似乎XrayR没有报告到v2board。

**Comment by wyx2685** [comment]
看看nginx的error日志呢

**Comment by Riverboat8865** [comment]
都是一些其他节点的错误。 ```
2023/10/21 00:08:20 [crit] 361#361: *30253 SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL handshaking, client: ip1, server: 0.0.0.0:443
2023/10/21 00:08:20 [crit] 361#361: *30250 SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL handshaking, client: ip1, server: 0.0.0.0:443
2023/10/21 02:00:01 [error] 361#361: *32119 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 108.162.226.83, server: subscription.com, request: "GET /api/v1/server/UniProxy/config?node_id=9&node_type=vless&token=token HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "subscription.com"
2023/10/21 02:01:46 [crit] 366#366: *1 connect() to unix:/run/php/php7.4-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 172.70.147.65, server: subscription.com, request: "GET /api/v1/server/UniProxy/config?node_id=8&node_type=vless&token=token HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "subscription.com"

```

**Comment by wyx2685** [comment]
@Riverboat8865 太怪了，完全没思路
说说怎么部署和配置的看

**Comment by Riverboat8865** [comment]
github git, go直接安装。我没有更新成功，打扰了。。。
