### ISSUE TITLE
vless+ws+tls in sing-box client

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/XrayR#12]
Hello, good day, thanks for your good script.
vless-ws-tls configurations do not work in the sing box client, how can we solve the problem?

**Comment by wyx2685** [comment]
what does 'no work' mean

**Comment by MrVb0** [comment]
I use your v2board https://github.com/wyx2685/v2board and xrayr https://github.com/wyx2685/XrayR,
vless-ws-tls config works in all clients except singbox.  
In Singgbox, this protocol does not even have ping and it seems that it is not defined. 
Of course, the problem is probably from the v2board side and I put the ticket in the wrong place.

**Comment by wyx2685** [comment]
singbox subscribe is experimental now
lol

**Comment by MrVb0** [comment]
I think this free application (Singbox) is the best choice for iPhone and I would be grateful if you focus more on this application in the next updates. 
I just recently installed your scripts and I am very happy with them and thank you very much for developing them.
