### ISSUE TITLE
无法使用ipv6地址，求帮助

### ISSUE THREAD

**Issue by 759071793** [wyx2685/XrayR#15]
ipv4地址没有问题，但是用ipv6地址就超时，可以ping

**Comment by wyx2685** [comment]
会不会其实是客户端IPV6没写对，xrayr监听应该是正常的

**Comment by 759071793** [comment]
感谢大佬回复，我确定v6地址是写对了的
现在只有手机，截图了v6连接提示的报错
![image](https://github.com/wyx2685/XrayR/assets/23308600/c7cfb19b-71bc-4e4b-891e-d8fbe0581046)
还请帮忙看看呢？我看ipv4监听的是0.0.0.0，会不会是v6需要监听[::]呢

**Comment by wyx2685** [comment]
看起来你的客户端用ipv6正常连接到了节点，但是协议没有跑通，再检查一下设置?

**Comment by 759071793** [comment]
我的v4已经是通的，按道理v6也应该通的，可是我安装了4台vps，分别是甲骨文新加坡，两个natvps，一个rn、一个绿云香港，全部都是v4随便通，可是v6就会像上面截图一样。
之前安装x-ui是正常的。

**Comment by 759071793** [comment]
已解决，域名问题。。。打扰了
