### ISSUE TITLE
运行之后报错。。。

### ISSUE THREAD

**Issue by GH6324** [wyx2685/XrayR#2]
./XrayR -config config.yml  之后

报错如下：

Panel Start fialed: users is null
panic: Panel Start fialed: users is null

goroutine 1 [running]:
log.Panicf({0x341b6ce?, 0x38b1f80?}, {0xc0007f9e80?, 0xc0007d6ab0?, 0x2c704e0?})
        log/log.go:391 +0x67
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0006a7b00)
        github.com/XrayR-project/XrayR/panel/panel.go:207 +0x565
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250

**Comment by wyx2685** [comment]
先配好面板，注册用户，开订阅确保有流量，配置好节点
应该就行了

**Comment by GH6324** [comment]
> 先配好面板，注册用户，开订阅确保有流量，配置好节点 应该就行了

可以了，感谢大佬
