### ISSUE TITLE
transmission protocol configuration

### ISSUE THREAD

**Issue by Mjeir** [wyx2685/XrayR#21]
Greetings and courtesy
Please help me about transmission protocol configuration.
  I use the following code to use VMess +WS and everything is fine.

{
   "path": "/",
   "headers": {
     "Host": "mysite.com"
   }
}

But when I use TCP or use Vless with any transmission protocol
In the V2rayNG program, the request host part remains empty.
Please write me the correct transmission protocol configuration that can be used in TCP and Vless.
Do you allow me to contact you via Telegram or WeChat so that I can provide you with my server information and make a Vless node for me at a cost or as a gift?
thank you

**Comment by wyx2685** [comment]
{
  "header": {
    "type": "http",
    "request": {
      "path": [
        "/"
      ],
      "headers": {
        "Host": [
          "www.baidu.com",
          "www.bing.com"
        ]
      }
    }
  }
}

**Comment by Mjeir** [comment]
Hello, dear professional
Is it possible to remove the http header?
When I delete it, the request host part remains empty!
i nead only vmess/vless TCP

thanks
