### ISSUE TITLE
流量统计不准确

### ISSUE THREAD

**Issue by Piggy-Page** [wyx2685/XrayR#24]
Reality节点看YouTub 4K视频测试时长30分钟 至少使用了几个G流量 但是节点显示只用了5MB流量
我看修改版的XrayR配置项不全，是不是没有开启流量统计功能？
![json](https://github.com/wyx2685/XrayR/assets/77221888/acd2010d-2a1a-4d3b-a116-8cdfdae71f4c)

**Comment by kevlau1** [comment]
> Reality节点看YouTub 4K视频测试时长30分钟 至少使用了几个G流量 但是节点显示只用了5MB流量

1.找1gb文件下载
2.过几分钟后台看流量统计，统计会有滞后
3.对比vps后台流量消耗
4.你这样反馈一点用都没有
