### ISSUE TITLE
配置了xrayr后端使用vless+tcp+vision后一直popup这个错误

### ISSUE THREAD

**Issue by matthewlu070111** [wyx2685/XrayR#26]
app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to find the default "name" config

**Comment by matthewlu070111** [comment]
解决方法，把前端tls关闭，tls与xtls不相兼容

**Comment by wyx2685** [comment]
说的都啥跟啥？
上具体配置吧，肯定哪个环节有问题
