### ISSUE TITLE
该脚本搭建的VLESS和TROJAN节点无法访问apple.com

### ISSUE THREAD

**Issue by forjustice** [wyx2685/XrayR#29]
如上所述。
但可以正常访问google.com，很奇怪。
换内核也是不管用的。

但是使用https://github.com/wyx2685/V2bX的VLESS节点是正常的。

**Comment by forjustice** [comment]
wyx2685/V2bX，是使用的singbox内核。

**Comment by wyx2685** [comment]
CN路由默认block
