### ISSUE TITLE
用户流量统计严重不准的问题

### ISSUE THREAD

**Issue by mickeywang626** [wyx2685/XrayR#30]
我用的你的v2board和改版的xrayR，节点工作正常，面板统计到的用户消耗的流量少的可怜，看了好久的油管视频，结果就统计了2MB左右，是怎么回事，求解

**Comment by wyx2685** [comment]
@mickeywang626 更新xray内核之后vless目前有这个现象，仍在排查中

**Comment by mickeywang626** [comment]
> @mickeywang626 更新xray内核之后vless目前有这个现象，仍在排查中

我如果用你wyx2685/XrayR的源代码，把其中的xray-core v1.8.10改成 老版本比如1.8.3，重新编译成一个xrayr文件，替换掉现有环境中的，有可能正常吗？

**Comment by mickeywang626** [comment]
1、部署环境：
    v2board：ubuntu20，xrayr：ubuntu22
    v2board采用的是你的改版代码，xrayr用的是你xray-release项目中的一键安装脚本

2、xrary config.yml配置说明
    基于你默认的只改动了如下项：ApiHost、ApiKey、NodeID、NodeType：v2ray、EnableVless: true、EnableREALITY: true、DisableLocalREALITYConfig: true。

3、面板添加vless协议关键配置
    安全性：reality
    传输协议：TCP
    XTLS流控算法：xtls-rprx-vision
    Server Name(sni)：www.python.org
    Server Port：443
    其他均是默认

现象描述：在稳定播放4k视频的情况下，流量时而增长时而不变，间隔不固定，增长也是涨几兆或者零点几兆，明显小于实际流量。
通过在push方法中加日志，捕捉xrayr推送流量统计信息发现，推送间隔也不稳定，有时候间隔好久都不推，有时候能检测到。
    日志加在的v1下面的UniProxyController中，如下
    // 后端提交数据
    public function push(Request $request)
    {
        $data = request()->getContent() ?: json_encode($_POST);
        info("流量推送:{$data}");  //增加的日志输出
        $data = json_decode($data, true);
        if ($data === null && json_last_error() !== JSON_ERROR_NONE) {
            // JSON decoding error
            return response([
                'error' => 'Invalid traffic data'
            ], 400);
        }
        ............

ps:我单独测试了原版xray-core 1.8.9版本的  xray api stats --server=127.0.0.1:10085 ,流量部署稳定正常。供参考

**Comment by mickeywang626** [comment]
感觉像是xrayr的捕获流量解析或者机制有问题，麻烦看看怎么搞

**Comment by wyx2685** [comment]
XTLS现在开启的splice会导致流量统计存在延迟，xrayr每分钟都取流量然后清空计数，导致延迟统计的流量可能被遗漏

**Comment by mickeywang626** [comment]
我看好像1.8.5的没有splice，我用你的代码改成这个版本编译可以吗？

**Comment by wyx2685** [comment]
暂时选择牺牲性能，请测试b97856484191145343eb30fd392cf3aacedae102
