### ISSUE TITLE
使用一段时间后xrayR会创建一个网卡名称为wg0的网卡吗？

### ISSUE THREAD

**Issue by udhh2** [wyx2685/XrayR#32]
感谢开源，想问下这个使用一段时间后就会创建名称为wg0的网卡并且获取一个cf的ipv6 这个是正常的吗？这个wg0网卡主要用于什么呢？谢谢。
![image](https://github.com/wyx2685/XrayR/assets/165897461/54a31c91-c635-4fae-ab41-5be44ab9ed66)

**Comment by wyx2685** [comment]
@udhh2 脚本默认开warp
用于代理cn方向流量

**Comment by udhh2** [comment]
感谢回复。想问下有办法关闭这个默认的warp吗？

**Comment by wyx2685** [comment]
@udhh2 改一下custom_outbound.json和route.json
