### ISSUE TITLE
How to compile this project

### ISSUE THREAD

**Issue by zeronxdev** [wyx2685/XrayR#37]
Hello, I want to ask you how to compile this project, I tried the command [ go build -o XrayR -ldflags "-s -w" ]
After compiling and booting, there is no network connection

**Comment by wyx2685** [comment]
any log?

**Comment by zeronxdev** [comment]
![hình ảnh_2024-04-19_185342906](https://github.com/wyx2685/XrayR/assets/160329349/3ef8c355-c3b5-41c1-95ce-cce3eb30ba1c)
log works normally, runs successfully, but there is no network connection, same config file but the release version has network, but the version I built myself does not, please help me

**Comment by zeronxdev** [comment]
Can you give me the command you use to build the project?
My desire is simply to make the time between data pulls faster than data pushes:((

**Comment by wyx2685** [comment]
go build -v -o build_assets/XrayR -trimpath -ldflags "-s -w -buildid="

almost same as yours

**Comment by zeronxdev** [comment]
ok thanks

**Comment by zeronxdev** [comment]
GOOD
