### ISSUE TITLE
Reality的SNI无法显示在V2board订阅里面

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/XrayR#4]
XrayR使用Reality配置, 我用小火箭读取你对应的V2board订阅后，无法自动得到SNI。如果手动添加SNI小火箭的配置中没有问题。不知道是XRayR, V2board的问题，还是小火箭的问题。

**Comment by wyx2685** [comment]
在v2board的节点设置，安全性设置旁边编辑，写入servername

**Comment by Riverboat8865** [comment]
Ok, 需要手动输入
