### ISSUE TITLE
最新版本在进行流媒体测试时异常崩溃

### ISSUE THREAD

**Issue by Corner98** [wyx2685/XrayR#40]
在做流媒体测试时发生异常崩溃，xrayr重启

May 23 14:53:37 formal-body XrayR[5963]: panic: runtime error: index out of range [-1]
May 23 14:53:37 formal-body XrayR[5963]: goroutine 51 [running]:
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc000f04300, {0x4a7e540, 0x78b40a0}, {{0x4a7e7e0, 0xc0046b4e50}, 0x968, 0x3})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:288 +0xd1d
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).connectTo(0xc0024f6aa0, 0xc0013ad020)
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:131 +0x4b
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).Send(0xc0024f6aa0, {0xc0014ff908, 0x1, 0x7fb8dfda7108?}, {0x4a87708?, 0xc0013ad020})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:174 +0x56
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Peer).SendBuffers(0xc00253f208, {0xc0014ff908, 0x1, 0x1})
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/peer.go:136 +0x202
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Peer).SendHandshakeInitiation(0xc00253f208, 0xb0?)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:136 +0x3fe
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Peer).SendStagedPackets(0xc00253f208)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:350 +0xe5
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Peer).SendKeepalive(0xc00253f208?)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:96 +0x205
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Device).upLocked(0xc00190c508)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:186 +0x1e5
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Device).changeState(0xc00190c508, 0x1)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:153 +0xce
May 23 14:53:37 formal-body XrayR[5963]: golang.zx2c4.com/wireguard/device.(*Device).Up(...)
May 23 14:53:37 formal-body XrayR[5963]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:210
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*tunnel).BuildDevice(0xc002406000, {0xc0000f4a00, 0xfc}, {0x4a87750, 0xc0024f6aa0})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/tun.go:73 +0x1cb
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).makeVirtualTun(0xc000156000, 0xc0024f6aa0)
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:248 +0xb9
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).processWireGuard(0xc000156000, {0x4a76650, 0xc000f04300})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:120 +0x2d8
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).Process(0xc000156000, {0x4a7e460, 0xc0024e5e30}, 0xc000fe6000, {0x4a76650, 0xc000f04300})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:138 +0x105
May 23 14:53:37 formal-body XrayR[5963]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000f04300, {0x4a7e460, 0xc0024e5e30}, 0xc000fe6000)
May 23 14:53:37 formal-body XrayR[5963]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:209 +0x3e2
May 23 14:53:37 formal-body XrayR[5963]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).routedDispatch(0xc00111a310, {0x4a7e460, 0xc0024e5e30}, 0xc000fe6000, {{0x4a7e738, 0xc0014b71c0}, 0x1bb, 0x2})
May 23 14:53:37 formal-body XrayR[5963]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:495 +0xda6
May 23 14:53:37 formal-body XrayR[5963]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch.func1()
May 23 14:53:37 formal-body XrayR[5963]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:294 +0x3e5
May 23 14:53:37 formal-body XrayR[5963]: created by github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch in goroutine 50
May 23 14:53:37 formal-body XrayR[5963]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:267 +0x48a
May 23 14:53:37 formal-body systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 23 14:53:37 formal-body systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 23 14:53:47 formal-body systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 1.
May 23 14:53:47 formal-body systemd[1]: Stopped XrayR Service.
May 23 14:53:47 formal-body systemd[1]: Started XrayR Service.
May 23 14:53:47 formal-body XrayR[6152]: XrayR 0.9.2 (A Xray backend that supports many panels)

**Comment by iquping** [comment]
遇到了同样的问题
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: panic: runtime error: index out of range [-1]
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: goroutine 86 [running]:
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc000ef8300, {0x4a7e540, 0x78b40a0}, {{0x4a7e7e0, 0xc002561390}, 0x968, 0x3})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:288 +0xd1d
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).connectTo(0xc004060aa0, 0xc00193dad0)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:131 +0x4b
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).Send(0xc004060aa0, {0xc00254e378, 0x1, 0x7f9c69b30108?}, {0x4a87708?, 0xc00193dad0})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:174 +0x56
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Peer).SendBuffers(0xc0026cd208, {0xc00254e378, 0x1, 0x1})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/peer.go:136 +0x202
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Peer).SendHandshakeInitiation(0xc0026cd208, 0xb0?)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:136 +0x3fe
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Peer).SendStagedPackets(0xc0026cd208)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:350 +0xe5
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Peer).SendKeepalive(0xc0026cd208?)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:96 +0x205
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Device).upLocked(0xc001906288)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:186 +0x1e5
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Device).changeState(0xc001906288, 0x1)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:153 +0xce
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard/device.(*Device).Up(...)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:210
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*tunnel).BuildDevice(0xc002504000, {0xc0000f4b40, 0xfc}, {0x4a87750, 0xc004060aa0})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/tun.go:73 +0x1cb
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).makeVirtualTun(0xc000d782a0, 0xc004060aa0)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:248 +0xb9
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).processWireGuard(0xc000d782a0, {0x4a76650, 0xc000ef8300})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:120 +0x2d8
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).Process(0xc000d782a0, {0x4a7e460, 0xc000d20ea0}, 0xc0010254a0, {0x4a76650, 0xc000ef8300})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:138 +0x105
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000ef8300, {0x4a7e460, 0xc000d20ea0}, 0xc0010254a0)
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:209 +0x3e2
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).routedDispatch(0xc00193fdc0, {0x4a7e460, 0xc000d20ea0}, 0xc0010254a0, {{0x4a7e738, 0xc00196ca30}, 0x1bb, 0x2})
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/wyx2685/XrayR/app/mydispatcher/default.go:495 +0xda6
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch.func1()
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/wyx2685/XrayR/app/mydispatcher/default.go:294 +0x3e5
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: created by github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch in goroutine 85
Mai 24 02:36:07 v2202405224842270584 XrayR[2756]: github.com/wyx2685/XrayR/app/mydispatcher/default.go:267 +0x48a
Mai 24 02:36:07 v2202405224842270584 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mai 24 02:36:07 v2202405224842270584 systemd[1]: XrayR.service: Failed with result 'exit-code'.
Mai 24 02:36:17 v2202405224842270584 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 20.
Mai 24 02:36:17 v2202405224842270584 systemd[1]: Stopped XrayR.service - XrayR Service.
