### ISSUE TITLE
对接多节点问题

### ISSUE THREAD

**Issue by Standarduse** [wyx2685/XrayR#41]
大佬你好，我用修改版的XrayR对接了一个vless节点，按照原版的XrayR方法在下面再对接一个Trojan节点，能启动成功，面板信号也变黄了，证明通讯了嘛，但节点ping不通，请大佬指点

**Comment by Standarduse** [comment]
没开防火墙的。。

**Comment by tools5** [comment]
@Standarduse 看日志

**Comment by Standarduse** [comment]
好的，等下我试试。因为日志我不太会看。哈哈

**Comment by Standarduse** [comment]
rejected  proxy/trojan: not a valid user
我单独对接一个Trojan对接成功了，但ping不通，这个是防火墙的问题吗

**Comment by Standarduse** [comment]
启动成功，机器后台已经开放了所有端口的，机场面板也有通讯，就是ping不通
