### ISSUE TITLE
最新版本（20240521）报错 panic: runtime error: index out of range [-1] ，经常反复自动重启

### ISSUE THREAD

**Issue by huah6571** [wyx2685/XrayR#43]
使用配套的v2b+reality
新版更新之后经常反复自动重启，log如下

May 25 15:25:58 vm001 XrayR[3706]: panic: runtime error: index out of range [-1]
May 25 15:25:58 vm001 XrayR[3706]: goroutine 1326 [running]:
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc000d44380, {0x4a7e540, 0x78b40a0}, {{0x4a7e7e0, 0xc001f02f50}, 0x968, 0x3})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:288 +0xd1d
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).connectTo(0xc001efd4a0, 0xc001f1b0b0)
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:131 +0x4b
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).Send(0xc001efd4a0, {0xc001f184c8, 0x1, 0x7fb3da899108?}, {0x4a87708?, 0xc001f1b0b0})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/bind.go:174 +0x56
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Peer).SendBuffers(0xc002667508, {0xc001f184c8, 0x1, 0x1})
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/peer.go:136 +0x202
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Peer).SendHandshakeInitiation(0xc002667508, 0xb0?)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:136 +0x3fe
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Peer).SendStagedPackets(0xc002667508)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:350 +0xe5
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Peer).SendKeepalive(0xc002667508?)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:96 +0x205
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Device).upLocked(0xc001908288)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:186 +0x1e5
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Device).changeState(0xc001908288, 0x1)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:153 +0xce
May 25 15:25:58 vm001 XrayR[3706]: golang.zx2c4.com/wireguard/device.(*Device).Up(...)
May 25 15:25:58 vm001 XrayR[3706]:         golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:210
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*tunnel).BuildDevice(0xc0023b6000, {0xc00238a000, 0xfc}, {0x4a87750, 0xc001efd4a0})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/tun.go:73 +0x1cb
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).makeVirtualTun(0xc000d783f0, 0xc001efd4a0)
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:248 +0xb9
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).processWireGuard(0xc000d783f0, {0x4a76650, 0xc000d44380})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:120 +0x2d8
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/proxy/wireguard.(*Handler).Process(0xc000d783f0, {0x4a7e460, 0xc001ef9d40}, 0xc001e9b5e0, {0x4a76650, 0xc000d44380})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/proxy/wireguard/client.go:138 +0x105
May 25 15:25:58 vm001 XrayR[3706]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000d44380, {0x4a7e460, 0xc001ef9d40}, 0xc001e9b5e0)
May 25 15:25:58 vm001 XrayR[3706]:         github.com/xtls/xray-core@v1.8.12-0.20240520040056-544f7661ca74/app/proxyman/outbound/handler.go:209 +0x3e2
May 25 15:25:58 vm001 XrayR[3706]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).routedDispatch(0xc001941dc0, {0x4a7e460, 0xc001ef9d40}, 0xc001e9b5e0, {{0x4a7e738, 0xc001466a60}, 0x50, 0x2})
May 25 15:25:58 vm001 XrayR[3706]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:495 +0xda6
May 25 15:25:58 vm001 XrayR[3706]: github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch.func1()
May 25 15:25:58 vm001 XrayR[3706]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:294 +0x3e5
May 25 15:25:58 vm001 XrayR[3706]: created by github.com/wyx2685/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch in goroutine 1325
May 25 15:25:58 vm001 XrayR[3706]:         github.com/wyx2685/XrayR/app/mydispatcher/default.go:267 +0x48a
May 25 15:25:58 vm001 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 25 15:25:58 vm001 systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 25 15:25:58 vm001 systemd[1]: XrayR.service: Consumed 1.680s CPU time.
May 25 15:26:08 vm001 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 11.
May 25 15:26:08 vm001 systemd[1]: Stopped XrayR Service.
May 25 15:26:08 vm001 systemd[1]: XrayR.service: Consumed 1.680s CPU time.
May 25 15:26:08 vm001 systemd[1]: Started XrayR Service.
May 25 15:26:09 vm001 XrayR[3731]: XrayR 0.9.2 (A Xray backend that supports many panels)
May 25 15:26:09 vm001 XrayR[3731]: 2024/05/25 15:26:09 Start the panel..
May 25 15:26:09 vm001 XrayR[3731]: 2024/05/25 15:26:09 [Debug] infra/conf: kernel mode is enabled as it's supported and permission is sufficient
May 25 15:26:09 vm001 XrayR[3731]: 2024/05/25 15:26:09 Xray Core Version: 1.8.11
May 25 15:26:09 vm001 XrayR[3731]: 2024/05/25 15:26:09 [Warning] core: Xray 1.8.11 started

**Comment by chibinyong** [comment]
同样的问题

**Comment by huah6571** [comment]
> 同样的问题

你也是香港的机器吗，他这个新版好像增加了一个wg0的warp网卡，用于接管回国流量。但是hk的机器貌似普通warp不能直接用

**Comment by wyx2685** [comment]
目测是上游xray的问题，新内核代码修了，请更新后测试
