### ISSUE TITLE
SS-metron使用reality报错

### ISSUE THREAD

**Issue by jameqq** [wyx2685/XrayR#44]
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: panic: runtime error: invalid memory address or nil pointer dereference
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x3343cf4]
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: goroutine 1 [running]:
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/service/controller.InboundBuilder(0xc002682870, 0xc001048800, {0xc0019b90f8, 0x13})
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/service/controller/inboundbuilder.go:229 +0x10f4
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/service/controller.(*Controller).addNewTag(0xc001a3aea0, 0xc001048800)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/service/controller/controller.go:327 +0x74
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/service/controller.(*Controller).Start(0xc001a3aea0)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/service/controller/controller.go:93 +0x225
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/panel.(*Panel).Start(0xc0019a3600)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/panel/panel.go:211 +0x5ff
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/cmd.run()
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/cmd/root.go:106 +0x1c5
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/cmd.init.func1(0xc0019b2700?, {0x444cc4b?, 0x4?, 0x444cb3b?})
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/cmd/root.go:27 +0x13
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/spf13/cobra.(*Command).execute(0x780d740, {0xc000072910, 0x2, 0x2})
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/spf13/cobra.(*Command).ExecuteC(0x780d740)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/spf13/cobra.(*Command).Execute(...)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/spf13/cobra@v1.8.0/command.go:1039
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: github.com/wyx2685/XrayR/cmd.Execute(...)
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/cmd/root.go:120
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]: main.main()
May 26 15:50:25 ip-172-26-13-184 XrayR[2310222]:         github.com/wyx2685/XrayR/main.go:9 +0x1a
May 26 15:50:25 ip-172-26-13-184 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 26 15:50:25 ip-172-26-13-184 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by wyx2685** [comment]
@jameqq 用原版吧 不太会修
