### ISSUE TITLE
自定义入口报错

### ISSUE THREAD

**Issue by fuchao2687** [wyx2685/XrayR#45]
报错日志如下：
Jul 18 20:34:01 HK XrayR[881545]: XrayR 0.9.3 (A Xray backend that supports many panels)
Jul 18 20:34:01 HK XrayR[881545]: 2024/07/18 20:34:01 Start the panel..
Jul 18 20:34:01 HK XrayR[881545]: 2024/07/18 20:34:01 Failed to understand Inbound config, Please check: https://xtls.github.io/config/inbound.html for help: infra/conf: Listen on AnyIP but no Port(s) set in InboundDetour.
Jul 18 20:34:01 HK XrayR[881545]: panic: Failed to understand Inbound config, Please check: https://xtls.github.io/config/inbound.html for help: infra/conf: Listen on AnyIP but no Port(s) set in InboundDetour.

填写的custom_inbound.json如下：
[
{
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 50000,
      "protocol": "VLESS",
      "settings": {
        "clients": [
          {
            "id": "idididid",
            "level": 0,
            "email": "t@t.tt",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "serverName": "www.python.org",
          "fingerprint": "chrome",
          "show": false,
          "publicKey": "publicKeypublicKeypublicKeypublicKey",
          "shortId": "shortId",
          "spiderX": ""
        }
      },
      "tag": "hk-in",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "allocate": {
        "strategy": "always"
      }
    }
  ]
}
	]
看上去好像是因为没有设置port，已经尝试"port": "50000"，也不行，不知道应该怎么解决，麻烦大佬指点一下谢谢

**Comment by wyx2685** [comment]
@fuchao2687 以下是这个文件的写法
[ 
    { 
      "listen": "127.0.0.1", 
      "port": 50000, 
      "protocol": "VLESS", 
      "settings": { 
        "clients": [ 
          { 
            "id": "idididid", 
            "level": 0, 
            "email": "t@t.tt", 
            "flow": "xtls-rprx-vision" 
          } 
        ], 
        "decryption": "none", 
        "fallbacks": [ 
          { 
            "dest": 80 
          } 
        ] 
      }, 
      "streamSettings": { 
        "network": "tcp", 
        "security": "reality", 
        "realitySettings": { 
          "serverName": "www.python.org", 
          "fingerprint": "chrome", 
          "show": false, 
          "publicKey": "publicKeypublicKeypublicKeypublicKey", 
          "shortId": "shortId", 
          "spiderX": "" 
        } 
      }, 
      "tag": "hk-in", 
      "sniffing": { 
        "enabled": true, 
        "destOverride": ["http", "tls"] 
      }, 
      "allocate": { 
        "strategy": "always" 
      } 
    } 
  ]
