### ISSUE TITLE
后端能否增加用户缓存

### ISSUE THREAD

**Issue by NiDeHaoDaGe** [wyx2685/XrayR#46]
也就是说 网站挂了并不影响最后一次获取到的用户数据 保证客户还能使用节点
我觉得网站挂不影响节点这个很有用 大佬有空看看能不能实现

**Comment by wyx2685** [comment]
@NiDeHaoDaGe 我记得原版网站挂了是不影响的
我在哪改了一下就影响了

**Comment by wyx2685** [comment]
看了下XrayR应该不会挂
