### ISSUE TITLE
流量统计功能缺失

### ISSUE THREAD

**Issue by geneyuriy** [wyx2685/XrayR#5]
管理后台和用户端都看不到流量使用情况

v2board和xrayR都是用的wyx2685 fork的最新版本

**Comment by wyx2685** [comment]
有详细信息不，用的协议，还有截图啥的

**Comment by zmd0910** [comment]
![image](https://github.com/wyx2685/XrayR/assets/3423557/51912bfb-2896-4503-8d1c-44c9ca876b05)

应该是这边上报数据为空导致

**Comment by zmd0910** [comment]
![image](https://github.com/wyx2685/XrayR/assets/3423557/ebe4a9d9-1649-42fd-91aa-dd1ef69f4f1a)
这个是正常上报数据的情况
