### ISSUE TITLE
[FeatureRequest] Add Observatory and BurstObservatory for Balancer

### ISSUE THREAD

**Issue by ariadarkkkis** [wyx2685/XrayR#50]
Hi,
please add Observatory and BurstObservatory for Balancer `leastPing` and `leastLoad` to work since these are needed for these balancer types.
Docs are here:
https://xtls.github.io/config/observatory.html

**Comment by wyx2685** [comment]
too much break change
try v2bx instead

**Comment by ariadarkkkis** [comment]
Does that work with SSPanel?

**Comment by wyx2685** [comment]
No

**Comment by wyx2685** [comment]
For sspanel you should use original XrayR
