### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by chrikman2** [wyx2685/XrayR#52]
Hello, have a good time
The warp function does not work on the updated version of xrayr
Thanks for checking it out

**Comment by wyx2685** [comment]
please give further information
i don't use xrayr now can't check

**Comment by chrikman2** [comment]
I want to pass the traffic of the website whatismyipaddress.com through warp using the following code
{
  "domain": [
    "geosite:cn",
    "whatismyipaddress.com"
  ],
  "outboundTag": "warp"
}
 By replacing the code and restarting the xrayr service, I do not receive any errors, but when I enter the above site, instead of one of the warp IPs being displayed to me, the main server IP is displayed.

**Comment by wyx2685** [comment]
@chrikman2 maybe ip address detect script is not store at whatismyipaddress.com doma

**Comment by wyx2685** [comment]
try this

{
"network": "tcp",
"outboundTag": "warp"
}

**Comment by chrikman2** [comment]
The following code works better for me
{
"domain": [
"geosite:cn",
"whatismyipaddress.com"
],
"outboundTag": "warp"
}
It seems that the problem is not with xraryr, I tested another site, the warp was executed well on that site 
Probably, this problem is related to using the free version of Warp, maybe it can be solved by providing a special key
In any case, thank you for all your hard work
good luck
