### ISSUE TITLE
配置文件"ApiHost":后面不能写域名加端口的配置

### ISSUE THREAD

**Issue by yamatu** [wyx2685/XrayR#53]
配置文件"ApiHost": "https://domain.xyz:7001这样填写后显示一下错误，程序貌似不支持带端口的ApiHost

Oct 04 21:00:04 us1 V2bX[43234]: V2bX v0.0.16 (A V2board backend based on multi core)
Oct 04 21:00:05 us1 V2bX[43234]: time="2024-10-04T21:00:05+08:00" level=error msg="Run nodes failed" err="start node controller [https://domain.xyz:7001-hysteria2-1] error: add users error: not have any user"
Oct 04 21:00:05 us1 systemd[1]: V2bX.service: Deactivated successfully.
Oct 04 21:00:15 us1 systemd[1]: V2bX.service: Scheduled restart job, restart counter is at 28.
Oct 04 21:00:15 us1 systemd[1]: Stopped V2bX.service - V2bX Service.
Oct 04 21:00:15 us1 systemd[1]: Started V2bX.service - V2bX Service.
Oct 04 21:00:15 us1 V2bX[43240]:  
Oct 04 21:00:15 us1 V2bX[43240]:   _/      _/    _/_/    _/        _/      _/
Oct 04 21:00:15 us1 V2bX[43240]:  _/      _/  _/    _/  _/_/_/      _/  _/
Oct 04 21:00:15 us1 V2bX[43240]: _/      _/      _/    _/    _/      _/
Oct 04 21:00:15 us1 V2bX[43240]:  _/  _/      _/      _/    _/    _/  _/
Oct 04 21:00:15 us1 V2bX[43240]:   _/      _/_/_/_/  _/_/_/    _/      _/
Oct 04 21:00:15 us1 V2bX[43240]:                                                 
Oct 04 21:00:15 us1 V2bX[43240]: V2bX v0.0.16 (A V2board backend based on multi core)

Oct 04 21:00:46 us1 V2bX[43240]: 2024/10/04 21:00:46.000591 WARN RESTY Get "https://domain.xyz/api/v1/server/UniProxy/config?node_id=1&node_type=hysteria2&token=123": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
Oct 04 21:01:16 us1 V2bX[43240]: 2024/10/04 21:01:16.101973 WARN RESTY Get "https://domain.xyz/api/v1/server/UniProxy/config?node_id=1&node_type=hysteria2&token=123": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2

**Comment by wyx2685** [comment]
@yamatu 你自己再看看吧，实在不行放弃吧
