### ISSUE TITLE
流量统计不支持倍率统计

### ISSUE THREAD

**Issue by Furota** [wyx2685/XrayR#8]
使用面板：https://github.com/wyx2685/V2board/
XrayR 0.9.1 安装方式
手动替换了 /usr/local/XrayR 中的程序文件，修改为支持reality的配置文件，并成功对接使用数天。
最近新增了一个0.01倍率的节点，发现倍率统计异常。
用户使用了4G流量，按照逻辑应该计费4\*0.01=0.04G，但是实际却是4\*100\*0.01来统计的。另外，后台面板总流量统计正常显示。
后面试了一下，确实复现了。请问是我部署方式的问题还是程序设计bug？如果是后者，希望大佬能修复这个问题。
![photo_2023-09-09_15-47-17](https://github.com/wyx2685/XrayR/assets/143926437/536797e9-69e4-4ed9-be46-e7ebc3e2c384)

**Comment by wyx2685** [comment]
需要确认用户是不是实际只用了4G流量
看起来应该是用了400G，倍率这个东西是不会传给后端的

**Comment by Furota** [comment]
由于V2B 1.7.4有隔天统计流量使用信息的特性，使得我的测试数据今天才能看到。
我使用面板设定为0.01倍率的节点跑了210M流量
用户侧显示为 
![image](https://github.com/wyx2685/XrayR/assets/143926437/03eae3ec-6553-4699-8fb6-7042a08a6222)
ADMIN侧显示为
![image](https://github.com/wyx2685/XrayR/assets/143926437/919d05cf-74d5-4a8c-a08f-4880450576ab)
如果倍率与后端无关，那我认为应该是配套面板的显示问题？
今天我会开一个空号再次测试，同时关闭XrayR的这个issue并在您的V2board发起新issue
