### ISSUE TITLE
custum_dns无法读取

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/XrayR#9]
自定义custom_dns导致XrayR panic:

custom_dns设置如下：
```
[
   "servers": [
      "https+local://1.1.1.1/dns-query", 
      "localhost"
   ]
]
```

**Comment by wyx2685** [comment]
{
   "servers": [
      "https+local://1.1.1.1/dns-query", 
      "localhost"
   ]
}

注意格式哈

**Comment by Riverboat8865** [comment]
{
   "servers": [
      "https+local://1.1.1.1/dns-query", 
      "localhost"
   ]
}
不行的

**Comment by wyx2685** [comment]
测试没有问题，请发panic日志

**Comment by Riverboat8865** [comment]
我的疏忽。
